---

- hosts: bigboi
  become: true
  vars:
    uri: "//192.168.55.7/public-media"
    mountpoint: "/mnt/public-media"

  roles:
    - role: samba
      become: yes
      tags:
        - samba

    - role: docker
      tags:
        - docker

    - role: containers/system/unifi
      become: yes
      tags:
        - unifi
        - containers
#  
#     - role: containers/media/jellyfin
#       become: no
#       tags:
#         - jellyfin
#         - containers
# 
